name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every midnight (UTC time)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: gauravshukla111
          outputs: dist/snake.svg

      - name: Upload Snake.svg
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Download Snake.svg
        uses: actions/download-artifact@v2
        with:
          name: snake

      - name: Push Snake to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
